name       : python-trimesh
version    : 3.16.4
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/t/trimesh/trimesh-3.16.4.tar.gz : 0f239031cab5e1e64c68b503e0df8491ead4c8a3ff7e6340eec9c6b9e1b05f48
homepage   : https://github.com/mikedh/trimesh
license    : MIT
component  : programming.python
summary    : Python library for loading and using triangular meshes
description: |
    Trimesh is a pure Python library for loading and using triangular meshes with an emphasis on watertight surfaces. The goal of the library is to provide a full featured and well tested Trimesh object which allows for easy manipulation and analysis, in the style of the Polygon object in the Shapely library.
rundeps    :
    - numpy
build      : |
    %python3_setup
install    : |
    %python3_install
